require:
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "gems/**/*"
    - "node_modules/**/*"
    - "Gemfile"
    - "Rakefile"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Exclude:
    - "test/integration/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SafeNavigationWithBlank:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Performance/Detect:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "test/**/*.rb"
    - "spec/**/*.rb"
